port: 5000
env:
  NODE_ENV: production
  DATABASE_URL: postgres://postgres:47b47cd6c33582dafa23@c5qiwz.easypanel.host:5432/ecosaber?sslmode=disable
  PGPASSWORD: 47b47cd6c33582dafa23
  PGUSER: postgres
  PGHOST: c5qiwz.easypanel.host
  PGDATABASE: ecosaber