port: 80
env:
  NODE_ENV: production
  DATABASE_URL: postgres://postgres:47b47cd6c33582dafa23@ia_ecosaber-database:5432/ecosaber?sslmode=disable
  PGPASSWORD: 47b47cd6c33582dafa23
  PGUSER: postgres
  PGHOST: ia_ecosaber-database
  PGDATABASE: ecosaber