version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ecosaber
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./ecosaber_backup.dump:/app/ecosaber_backup.dump

  db-init:
    build: .
    depends_on:
      - db
    environment:
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=ecosaber
    command: ./init-db.sh
    volumes:
      - ./ecosaber_backup.dump:/app/ecosaber_backup.dump

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecosaber
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  postgres_data: